"""Initial migration

Revision ID: b34c8fa0b414
Revises: 
Create Date: 2025-10-10 14:01:07.767992

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "b34c8fa0b414"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
